language: kotlin

jdk: oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)