language: kotlin

jdk: oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - gradle assemble
  - gradle build
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)