language: kotlin

jdk: oraclejdk8

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks: https://hook.bearychat.com/=bwAy5/travis/4ab56d4590c667a0997966ff17c08570