version: "{branch} {build}"
services: mysql
build:
  verbosity: detailed

build_script:
  - gradlew.bat build --info

branches:
  only:
    - master

environment:
  matrix:
  # don't let this fool you, we still build to target java7
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
