version: "{branch} {build}"
services: mysql
build:
  verbosity: detailed

build_script:
  - gradle assemble
  - gradle build

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  # don't let this fool you, we still build to target java7
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
